language: ruby
rvm:
  - 1.9.3
  - 2.0.0
bundler_args: --without test
branches:
  only:
    - master
addons:
  code_climate:
    repo_token: d2565426bec84943089cd897d8847bbe11d18912481dac2d16d0b60ff14b0453
