sudo: false
language: ruby
rvm:
  - 1.9
  - 2.0
  - 2.1
  - 2.2
  - 2.3
before_install:
  - gem install bundler
  - openssl version
  - openssl list-standard-commands | grep 'cms'
addons:
  code_climate:
    repo_token: d2565426bec84943089cd897d8847bbe11d18912481dac2d16d0b60ff14b0453
after_success:
  - bundle exec codeclimate-test-reporter
script:
  - bundle exec rake travis
addons:
  code_climate:
    repo_token: d2565426bec84943089cd897d8847bbe11d18912481dac2d16d0b60ff14b0453
