sudo: false
language: ruby
rvm:
  - 1.9
  - 2.0
  - 2.1
  - 2.2
  - 2.3.1
before_install:
  - gem install bundler
  - openssl version
  - openssl list-standard-commands | grep 'cms'
addons:
  code_climate:
    repo_token: 4050944d6bc40c588421f51fc7f2b6fa31c3a338c03786a9359d148ecdbbe68e
after_success:
  - bundle exec codeclimate-test-reporter
script:
  - bundle exec rake travis
